### ISSUE TITLE
Generate wdio tests template.

### ISSUE THREAD

**Issue by rakshith91** [cerner/generator-terra-module#83]
### Description of Issue
Currently, only jest and nightwatch templates are generated. Template for wdio tests must be included.

### Expected Outcomes
- The tests folder includes wdio template.

**Comment by emilyrohrbough** [comment]
This issue was addressed in this PR https://github.com/cerner/generator-terra-module/pull/82 merged two days ago. Upon the newest release, you'll have access to wdio templates. 

On that note, our team is migrating away from nightwatch testing, so this change no longer provides a nightwatch template.

**Comment by emilyrohrbough** [comment]
v1.6.0 was released. Wdio templates are now available within the generator.
